name: CI

on:
  push:
    branches:
      - master
      - tmp
  pull_request:
    paths:
    - '**.zig'
    - '**.c'
    - '**.h'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Fmt
        run: zig fmt . --check
        if: matrix.os == 'ubuntu-latest'

      - name: Build
        run: zig build

      - name: Build 32-bit
        run: zig build -Dtarget=arm-linux
        if: matrix.os == 'ubuntu-latest'

      - name: Build release
        run: zig build -Doptimize=ReleaseSafe

      - name: Run Tests
        run: zig build test
