name: CI

on:
  push:
    branches:
      - master
      - tmp
  pull_request:
    paths:
    - '**.zig'
    - '**.c'
    - '**.h'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Build
        run: zig build

      - name: Include libc headers
        run: |
          zig-out/bin/arocc "libc headers.c" -fsyntax-only
        
