name: CI

on:
  push:
  pull_request:
    paths:
    - '**.zig'
    - '**.c'
    - '**.h'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master

      - name: Build
        run: zig build

      - name: Fmt
        run: zig fmt .

      - name: Run Tests
        run: zig build test
